baseURL = "https://hugo-theme-shell.netlify.app/"
languageCode = "en-us"
title = "Mohamed Aziz Fadhel Website"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "monokai"
    userName = "fadh"
    pcName = "pc"
    workDir = "whoami"
    profile = "profile.txt"
    
    description = """
    ICT engineering student and a cloud security engineer wannabe 
    CTF player 
    Passionate about Ethical Hacking and Penetration Testing 
  
  """
    
    
 
    [Params.Tree]
    use = true
    folderName = "Reach_Me"
    files = [
        ["Linkedin - ", "https://www.linkedin.com/in/mohamed-aziz-el-fadhel-b85431233/"],
        ["TryHackMe - ", "https://tryhackme.com/p/MoFahdel"],
        ["LetsDefend - ", "https://app.letsdefend.io/public-profile/user/MoFahdel/05d81f9b-385e-47fd-9ffc-5186caf9f649"],
        ["Github -", "https://github.com/MohamedAzizFadhel"],
        ["Email - mohamedaziz.elfadhel@etudiant-enit.utm.tn ", "https://master--mohamedazizfadhel.netlify.app/"]
        
    ]
